[build]
  command = "npm run build:ssr && npm run prerender"
  publish = "dist/hexacore/browser"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
