[build]
  command = "npm run build:ssr && ng run hexacore:server"
  publish = "dist/hexacore/browser"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
