[build]
  command = "npm run build:ssr && npm run hexacore:server"
  publish = "dist/hexacore/browser"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
